FROM primestrategy/kusanagi-php7
#RUN apk add --no-cache mysql-client && usermod -u 1001 www-data && groupmod -g 1001 www-data
RUN apk add --no-cache mysql-client git openssh \
    && apk add --no-cache --virtual .build-gd libjpeg-turbo-dev libpng-dev \
    && docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr \
    && docker-php-ext-install gd \
    && apk del .build-gd \
    && deluser www-data \
    #&& delgroup www-data \
    && addgroup -g 1001 -S www-data \
    && adduser -u 1001 -D -S -G www-data www-data
